services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "5050:80"
    volumes:
      - react-data:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  react-data:
