services:
  react-ui:
    image: react-app
    container_name: react-ui
    ports:
      - "5050:80"
    volumes:
      - react-logs:/var/log/nginx
    networks:
      - react-net

volumes:
  react-logs:

networks:
  react-net:
